annotations:
  category: Infrastructure
  flavor: sha256:1e1b4657a77f0d47e9220f0c37b9bf7802581b93214fff7d1bd2364c8bf22e8e
  images: |
    - name: memcached
      image: registry-1.docker.io/bitnami/memcached:1.6.23-debian-11-r20
    - name: memcached-exporter
      image: registry-1.docker.io/bitnami/memcached-exporter:0.14.2-debian-11-r22
    - name: os-shell
      image: registry-1.docker.io/bitnami/os-shell:11-debian-11-r112
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.6.23
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.15.2
description: Memcached is an high-performance, distributed memory object caching system,
  generic in nature, but intended for use in speeding up dynamic web applications
  by alleviating database load.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/memcached/img/memcached-stack-220x234.png
keywords:
- memcached
- cache
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: memcached
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/memcached
version: 6.11.5
