annotations:
  category: Database
  flavor: sha256:1e1b4657a77f0d47e9220f0c37b9bf7802581b93214fff7d1bd2364c8bf22e8e
  images: |
    - image: registry-1.docker.io/bitnami/mariadb:11.2.2-debian-11-r6
      name: mariadb
    - image: registry-1.docker.io/bitnami/mysqld-exporter:0.15.1-debian-11-r5
      name: mysqld-exporter
    - image: registry-1.docker.io/bitnami/os-shell:11-debian-11-r96
      name: os-shell
  licenses: Apache-2.0
apiVersion: v2
appVersion: 11.2.2
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.14.1
description: MariaDB is an open source, community-developed SQL database server that
  is widely in use around the world due to its enterprise features, flexibility, and
  collaboration with leading tech firms.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
keywords:
- mariadb
- mysql
- database
- sql
- prometheus
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: mariadb
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mariadb
version: 15.2.3
